### ISSUE TITLE
One or more plugins require a higher Android NDK version.

### ISSUE THREAD

**Issue by sajjad-salam** [Aashu-Dubey/flutter-samples#4]

**Comment by amitkumarsingh01** [comment]
Go to \yourapp\android\app\build.gradle: and change your file as 
### Before 
android {
    namespace "com.example.yourapp"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion
    
Image
![image](https://github.com/Aashu-Dubey/flutter-samples/assets/134759689/430242f9-48e0-4293-b96b-d6d15abe0efd)

### After
android {
    namespace "com.example.yourapp"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion "26.0.7326110"
    
Image
![image](https://github.com/Aashu-Dubey/flutter-samples/assets/134759689/304ca266-448e-4d78-ac2b-827f33142d9a)

**Comment by Aashu-Dubey** [comment]
Hi, I know it's been a while since this issue was created, but as explained by @itheaks the error can fixed by specifying the particular higher required NDK version in `app\build.gradle` file.
Which is also mentioned in the error log:
<img width="901" alt="Screenshot 2024-06-11 at 11 49 10 PM" src="https://github.com/Aashu-Dubey/flutter-samples/assets/46301285/6486db36-ee00-41b5-b2c8-83599bb2541c">

Plus the project is also upgraded to the latest v3.22.2, which might fix some other compatibility issues as well, so I'll be closing the issue now!
